a
No exception
b
Uncaught exception Backtrace_slots.Error("b")
Raised at Backtrace_slots.f in file "backtrace_slots.ml", line 43, characters 32-49
Called from Backtrace_slots.f in file "backtrace_slots.ml", line 43, characters 59-72
Called from Backtrace_slots.f in file "backtrace_slots.ml", line 43, characters 59-72
Called from Backtrace_slots.f in file "backtrace_slots.ml", line 43, characters 59-72
Called from Backtrace_slots.f in file "backtrace_slots.ml", line 43, characters 59-72
Called from Backtrace_slots.f in file "backtrace_slots.ml", line 43, characters 59-72
Called from Backtrace_slots.g in file "backtrace_slots.ml", line 46, characters 6-13
Re-raised at Backtrace_slots.g in file "backtrace_slots.ml", line 54, characters 4-13
Called from Backtrace_slots.run in file "backtrace_slots.ml", line 59, characters 11-23
Uncaught exception Backtrace_slots.Error("c")
Raised at Backtrace_slots.g in file "backtrace_slots.ml", line 55, characters 17-34
Called from Backtrace_slots.run in file "backtrace_slots.ml", line 59, characters 11-23
Uncaught exception Backtrace_slots.Error("d")
Raised at Backtrace_slots.f in file "backtrace_slots.ml", line 43, characters 32-49
Called from Backtrace_slots.f in file "backtrace_slots.ml", line 43, characters 59-72
Called from Backtrace_slots.f in file "backtrace_slots.ml", line 43, characters 59-72
Called from Backtrace_slots.f in file "backtrace_slots.ml", line 43, characters 59-72
Called from Backtrace_slots.f in file "backtrace_slots.ml", line 43, characters 59-72
Called from Backtrace_slots.f in file "backtrace_slots.ml", line 43, characters 59-72
Called from Backtrace_slots.g in file "backtrace_slots.ml", line 46, characters 6-13
Called from Backtrace_slots.run in file "backtrace_slots.ml", line 59, characters 11-23
Uncaught exception Invalid_argument("index out of bounds")
Raised at Backtrace_slots.run in file "backtrace_slots.ml", line 59, characters 14-22
